<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = '/var/www/drupal9';

return array(
    $vendorDir . '/pear/pear_exception',
    $vendorDir . '/pear/console_getopt',
    $vendorDir . '/pear/pear-core-minimal/src',
    $vendorDir . '/pear/archive_tar',
);
